openapi: 3.0.0
info:
  title: Process discovery service
  description: Simple service used to mine a process model by use of the inductive miner
  version: v1
  contact:
    email: hpl002@uib.com
servers:
- url: https://localhost:8080/api
  variables: {}
paths:
  /discover:
    post:
      tags:
      - Misc
      summary: discover
      operationId: discover
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - file
              type: object
              properties:
                file:
                  type: string
        required: false
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /translate:
    post:
      tags:
      - Misc
      summary: translate
      operationId: translate
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - file
              type: object
              properties:
                file:
                  type: string
        required: false
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /doc:
    get:
      tags:
      - Misc
      summary: doc
      operationId: doc
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
tags:
- name: Misc
  description: ''