openapi: 3.0.0
info:
  title: Process discovery service
  description: Simple service used to mine a process model by use of the inductive miner
  version: v1
  contact:
    email: hpl002@uib.com
servers:
  - url: 'localhost:3000/api/'
paths:
  /swagger.json:
    get:
      responses:
        '200':
          description: view swagger definition
  /discover:
    post:
      responses:
        '200':
          description: Mine a process tree from a .xes log by use of the inductive miner
  /translate:
    post:
      responses:
        '200':
          description: translate a process tree to bpmn diagram
   