openapi: 3.0.0
info:
  title: discovery_service
  contact: {}
  version: '1.0'
servers:
- url: http://localhost:8080/api
  variables: {}
paths:
  /discover:
    post:
      tags:
      - Misc
      summary: discover
      description: "Discover a process-tree by use of the heuristic miner. \nRequired an event log in specified in .xes format."
      operationId: discover
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - log
              type: object
              properties:
                log:
                  type: string
                  description: the log file
        required: false
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /translate/petri:
    post:
      tags:
      - Misc
      summary: translate petri
      description: Translates a process-tree to a valid patri-net.
      operationId: translatepetri
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - tree
              type: object
              properties:
                tree:
                  type: string
        required: false
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /doc:
    get:
      tags:
      - Misc
      summary: doc
      description: endpoint for viewing this api spec in swagger-ui
      operationId: doc
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /evaluate:
    post:
      tags:
      - Misc
      summary: evaluate
      description: >-
        # Endpoint for performing different evaluation functions.


        For more details about the specifics of these employed methods i diverge to the library documentation: https://pm4py.fit.fraunhofer.de/documentation#evaluation


        ### Replay fitness


        -  replayFitnessTokenBased

        - replaysFitnessAlignmentBased


        ### precision


        - precisionETConformance


        - precisionAlignETConformance




        ### generalization


        - generalization


        ### generalization


        ### simplicity


        - simplicity
      operationId: evaluate
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - tree
              - log
              - methods
              type: object
              properties:
                tree:
                  type: string
                log:
                  type: string
                methods:
                  $ref: '#/components/schemas/methods'
        required: false
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /rolediscovery:
    post:
      tags:
      - Misc
      summary: role discovery
      description: https://pm4py.fit.fraunhofer.de/documentation#item-11-5
      operationId: rolediscovery
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - log
              type: object
              properties:
                log:
                  type: string
        required: false
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /translate/bpmn:
    post:
      tags:
      - Misc
      summary: translate BPMN
      description: Translates a process-tree to a valid BPMN model.
      operationId: translateBPMN
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - tree
              type: object
              properties:
                tree:
                  type: string
        required: false
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    methods:
      title: methods
      required:
      - replayFitnessTokenBased
      - replaysFitnessAlignmentBased
      - precisionETConformance
      - precisionAlignETConformance
      - generalization
      - simplicity
      type: object
      properties:
        replayFitnessTokenBased:
          type: boolean
        replaysFitnessAlignmentBased:
          type: boolean
        precisionETConformance:
          type: boolean
        precisionAlignETConformance:
          type: boolean
        generalization:
          type: boolean
        simplicity:
          type: boolean
      example:
        replayFitnessTokenBased: false
        replaysFitnessAlignmentBased: false
        precisionETConformance: false
        precisionAlignETConformance: false
        generalization: false
        simplicity: false
tags:
- name: Misc
  description: ''
